// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNdhH1_j5k6pfT4cq0IzRhNhny4O8CENE',
    appId: '1:1011667573366:web:f87ab4a50b38b338a31d57',
    messagingSenderId: '1011667573366',
    projectId: 'proyecto1-4c9a2',
    authDomain: 'proyecto1-4c9a2.firebaseapp.com',
    storageBucket: 'proyecto1-4c9a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiw3oiRW5OMyCBb0Qfgb44o_xeRT3fxD4',
    appId: '1:1011667573366:android:f50efd3b50f793c8a31d57',
    messagingSenderId: '1011667573366',
    projectId: 'proyecto1-4c9a2',
    storageBucket: 'proyecto1-4c9a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMK20CxvuAqlw_SfJrkDFEekRheRV0aF0',
    appId: '1:1011667573366:ios:73a813bcf718df72a31d57',
    messagingSenderId: '1011667573366',
    projectId: 'proyecto1-4c9a2',
    storageBucket: 'proyecto1-4c9a2.appspot.com',
    iosClientId: '1011667573366-m8mhpqbecid83o00gq0qak1u0vt5f3lm.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto119400617',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMK20CxvuAqlw_SfJrkDFEekRheRV0aF0',
    appId: '1:1011667573366:ios:73a813bcf718df72a31d57',
    messagingSenderId: '1011667573366',
    projectId: 'proyecto1-4c9a2',
    storageBucket: 'proyecto1-4c9a2.appspot.com',
    iosClientId: '1011667573366-m8mhpqbecid83o00gq0qak1u0vt5f3lm.apps.googleusercontent.com',
    iosBundleId: 'mx.edu.ittepic.damU4Proyecto119400617',
  );
}
